use windows_sys::{
    core::*, 
    Win32::UI::WindowsAndMessaging::*,
};

pub struct SysMetsItem {
	pub index: i32,
	pub label: *const u8,
	pub desc: *const u8,
}

pub const SYS_METRICS: [SysMetsItem; 75] = [	// 75
	SysMetsItem { index: SM_CXSCREEN,			label: s!("SM_CXSCREEN"),
												desc: s!("Screen width in pixcels"),},
	SysMetsItem { index: SM_CYSCREEN,			label: s!("SM_CYSCREEN"),
												desc: s!("Screen height in pixels"),},
	SysMetsItem { index: SM_CXVSCROLL,			label: s!("SM_CXVSCROLL"),
												desc: s!("Vertical scroll width"),},
	SysMetsItem { index: SM_CYHSCROLL,			label: s!("SM_CYHSCROLL"),
												desc: s!("Horizontal scroll height"),},
	SysMetsItem { index: SM_CYCAPTION,			label: s!("SM_CYCAPTION"),
												desc: s!("Caption bar height"),},
	SysMetsItem { index: SM_CXBORDER,			label: s!("SM_CXBORDER"),
												desc: s!("Window border width"),},
	SysMetsItem { index: SM_CYBORDER,			label: s!("SM_CYBORDER"),
												desc: s!("Window border height"),},
	SysMetsItem { index: SM_CXFIXEDFRAME,		label: s!("SM_CXFIXEDFRAME"),
												desc: s!("Dialog window frame width"),},
	SysMetsItem { index: SM_CYFIXEDFRAME,		label: s!("SM_CYFIXEDFRAME"),
												desc: s!("Dialog window frame height"),},
	SysMetsItem { index: SM_CYVTHUMB,			label: s!("SM_CYVTHUMB"),
												desc: s!("Vertical scroll thumb height"),},
	SysMetsItem { index: SM_CXHTHUMB,			label: s!("SM_CXHTHUMB"),
												desc: s!("Horizontal scroll thumb width"),},
	SysMetsItem { index: SM_CXICON,				label: s!("SM_CXICON"),
												desc: s!("Icon width"),},
	SysMetsItem { index: SM_CYICON,				label: s!("SM_CYICON"),
												desc: s!("Icon height"),},
	SysMetsItem { index: SM_CXCURSOR,			label: s!("SM_CXCURSOR"),
												desc: s!("Cursor width"),},
	SysMetsItem { index: SM_CYCURSOR,			label: s!("SM_CYCURSOR"),
												desc: s!("Cursor height"),},
	SysMetsItem { index: SM_CYMENU,				label: s!("SM_CYMENU"),
												desc: s!("Menu bar height"),},
	SysMetsItem { index: SM_CXFULLSCREEN,		label: s!("SM_CXFULLSCREEN"),
												desc: s!("Full screen client area width"),},
	SysMetsItem { index: SM_CYFULLSCREEN,		label: s!("SM_CYFULLSCREEN"),
												desc: s!("Full screen client area height"),},
	SysMetsItem { index: SM_CYKANJIWINDOW,		label: s!("SM_CYKANJIWINDOW"),
												desc: s!("Kanji window height"),},
	SysMetsItem { index: SM_MOUSEPRESENT,		label: s!("SM_MOUSEPRESENT"),
												desc: s!("Mouse present flag"),},
	SysMetsItem { index: SM_CYVSCROLL,			label: s!("SM_CYVSCROLL"),
												desc: s!("Vertical scroll arrow height"),},
	SysMetsItem { index: SM_CXHSCROLL,			label: s!("SM_CXHSCROLL"),
												desc: s!("Horizontal scroll arrow width"),},
	SysMetsItem { index: SM_DEBUG,				label: s!("SM_DEBUG"),
												desc: s!("Debug version flag"),},
	SysMetsItem { index: SM_SWAPBUTTON,			label: s!("SM_SWAPBUTTON"),
												desc: s!("Mouse buttons swapped flag"),},
	SysMetsItem { index: SM_CXMIN,				label: s!("SM_CXMIN"),
												desc: s!("Minimum window width"),},
	SysMetsItem { index: SM_CYMIN,				label: s!("SM_CYMIN"),
												desc: s!("Minimum window height"),},
	SysMetsItem { index: SM_CXSIZE,				label: s!("SM_CXSIZE"),
												desc: s!("Min/Max/Close button width"),},
	SysMetsItem { index: SM_CYSIZE,				label: s!("SM_CYSIZE"),               
												desc: s!("Min/Max/Close button height"),},
	SysMetsItem { index: SM_CXSIZEFRAME,		label: s!("SM_CXSIZEFRAME"),
												desc: s!("Window sizing frame width"),},
	SysMetsItem { index: SM_CYSIZEFRAME,		label: s!("SM_CYSIZEFRAME"),
												desc: s!("Window sizing frame height"),},
	SysMetsItem { index: SM_CXMINTRACK,			label: s!("SM_CXMINTRACK"),
												desc: s!("Minimum window tracking width"),},
	SysMetsItem { index: SM_CYMINTRACK,			label: s!("SM_CYMINTRACK"),
												desc: s!("Minimum window tracking height"),},
	SysMetsItem { index: SM_CXDOUBLECLK,		label: s!("SM_CXDOUBLECLK"),
												desc: s!("Double click x tolerance"),},
	SysMetsItem { index: SM_CYDOUBLECLK,		label: s!("SM_CYDOUBLECLK"),
												desc: s!("Double click y tolerance"),},
	SysMetsItem { index: SM_CXICONSPACING,		label: s!("SM_CXICONSPACING"),
												desc: s!("Horizontal icon spacing"),},
	SysMetsItem { index: SM_CYICONSPACING,		label: s!("SM_CYICONSPACING"),
												desc: s!("Vertical icon spacing"),},
	SysMetsItem { index: SM_MENUDROPALIGNMENT,	label: s!("SM_MENUDROPALIGNMENT"),
												desc: s!("Left or right menu drop"),},
	SysMetsItem { index: SM_PENWINDOWS,			label: s!("SM_PENWINDOWS"),
												desc: s!("Pen extensions installed"),},
	SysMetsItem { index: SM_DBCSENABLED,		label: s!("SM_DBCSENABLED"),
												desc: s!("Double-Byte Char Set enabled"),},
	SysMetsItem { index: SM_CMOUSEBUTTONS,		label: s!("SM_CMOUSEBUTTONS"),
												desc: s!("Number of mouse buttons"),},
	SysMetsItem { index: SM_SECURE,				label: s!("SM_SECURE"),
												desc: s!("Security present flag"),},
	SysMetsItem { index: SM_CXEDGE,				label: s!("SM_CXEDGE"),
												desc: s!("3-D border width"),},
	SysMetsItem { index: SM_CYEDGE,				label: s!("SM_CYEDGE"),
												desc: s!("3-D border height"),},
	SysMetsItem { index: SM_CXMINSPACING,		label: s!("SM_CXMINSPACING"),
												desc: s!("Minimized window spacing width"),},
	SysMetsItem { index: SM_CYMINSPACING,		label: s!("SM_CYMINSPACING"),
												desc: s!("Minimized window spacing height"),},
	SysMetsItem { index: SM_CXSMICON,			label: s!("SM_CXSMICON"),
												desc: s!("Small icon width"),},
	SysMetsItem { index: SM_CYSMICON,			label: s!("SM_CYSMICON"),
												desc: s!("Small icon height"),},
	SysMetsItem { index: SM_CYSMCAPTION,		label: s!("SM_CYSMCAPTION"),
												desc: s!("Small caption height"),},
	SysMetsItem { index: SM_CXSMSIZE,			label: s!("SM_CXSMSIZE"),
												desc: s!("Small caption button width"),},
	SysMetsItem { index: SM_CYSMSIZE,			label: s!("SM_CYSMSIZE"),
												desc: s!("Small caption button height"),},
	SysMetsItem { index: SM_CXMENUSIZE,			label: s!("SM_CXMENUSIZE"),
												desc: s!("Menu bar button width"),},
	SysMetsItem { index: SM_CYMENUSIZE,			label: s!("SM_CYMENUSIZE"),
												desc: s!("Menu bar button height"),},
	SysMetsItem { index: SM_ARRANGE,			label: s!("SM_ARRANGE"),
												desc: s!("How minimized windows arranged"),},
	SysMetsItem { index: SM_CXMINIMIZED,		label: s!("SM_CXMINIMIZED"),
												desc: s!("Minimized window width"),},
	SysMetsItem { index: SM_CYMINIMIZED,		label: s!("SM_CYMINIMIZED"),
												desc: s!("Minimized window height"),},
	SysMetsItem { index: SM_CXMAXTRACK,			label: s!("SM_CXMAXTRACK"),
												desc: s!("Maximum draggable width"),},
	SysMetsItem { index: SM_CYMAXTRACK,			label: s!("SM_CYMAXTRACK"),
												desc: s!("Maximum draggable height"),},
	SysMetsItem { index: SM_CXMAXIMIZED,		label: s!("SM_CXMAXIMIZED"),
												desc: s!("Width of maximized window"),},
	SysMetsItem { index: SM_CYMAXIMIZED,		label: s!("SM_CYMAXIMIZED"),
												desc: s!("Height of maximized window"),},
	SysMetsItem { index: SM_NETWORK,			label: s!("SM_NETWORK"),
												desc: s!("Network present flag"),},
	SysMetsItem { index: SM_CLEANBOOT,			label: s!("SM_CLEANBOOT"),
												desc: s!("How system was booted"),},
	SysMetsItem { index: SM_CXDRAG,				label: s!("SM_CXDRAG"),
												desc: s!("Avoid drag x tolerance"),},
	SysMetsItem { index: SM_CYDRAG,				label: s!("SM_CYDRAG"),
												desc: s!("Avoid drag y tolerance"),},
	SysMetsItem { index: SM_SHOWSOUNDS,			label: s!("SM_SHOWSOUNDS"),
												desc: s!("Present sounds visually"),},
	SysMetsItem { index: SM_CXMENUCHECK,		label: s!("SM_CXMENUCHECK"),
												desc: s!("Menu check-mark width"),},
	SysMetsItem { index: SM_CYMENUCHECK,		label: s!("SM_CYMENUCHECK"),
												desc: s!("Menu check-mark height"),},
	SysMetsItem { index: SM_SLOWMACHINE,		label: s!("SM_SLOWMACHINE"),
												desc: s!("Slow processor flag"),},
	SysMetsItem { index: SM_MIDEASTENABLED,		label: s!("SM_MIDEASTENABLED"),
												desc: s!("Hebrew and Arabic enabled flag"),},
	SysMetsItem { index: SM_MOUSEWHEELPRESENT,	label: s!("SM_MOUSEWHEELPRESENT"),
												desc: s!("Mouse wheel present flag"),},
	SysMetsItem { index: SM_XVIRTUALSCREEN,		label: s!("SM_XVIRTUALSCREEN"),
												desc: s!("Virtual screen x origin"),},
	SysMetsItem { index: SM_YVIRTUALSCREEN,		label: s!("SM_YVIRTUALSCREEN"),
												desc: s!("Virtual screen y origin"),},
	SysMetsItem { index: SM_CXVIRTUALSCREEN,	label: s!("SM_CXVIRTUALSCREEN"),
												desc: s!("Virtual screen width"),},
	SysMetsItem { index: SM_CYVIRTUALSCREEN,	label: s!("SM_CYVIRTUALSCREEN"),
												desc: s!("Virtual screen height"),},
	SysMetsItem { index: SM_CMONITORS,			label: s!("SM_CMONITORS"),
												desc: s!("Number of monitors"),},
	SysMetsItem { index: SM_SAMEDISPLAYFORMAT,	label: s!("SM_SAMEDISPLAYFORMAT"),
												desc: s!("Same color format flag") },
];