// Custom MESSAGEBOX_RESULT
// use in dialog procedure

use windows::Win32::UI::WindowsAndMessaging::MESSAGEBOX_RESULT;
pub const COLOR_BLACK:MESSAGEBOX_RESULT = MESSAGEBOX_RESULT(IDC_BLACK);
pub const COLOR_BLUE:MESSAGEBOX_RESULT = MESSAGEBOX_RESULT(IDC_BLACK + 1);
pub const COLOR_GREEN:MESSAGEBOX_RESULT = MESSAGEBOX_RESULT(IDC_BLACK + 2);
pub const COLOR_CYAN:MESSAGEBOX_RESULT = MESSAGEBOX_RESULT(IDC_BLACK + 3);
pub const COLOR_RED:MESSAGEBOX_RESULT = MESSAGEBOX_RESULT(IDC_BLACK + 4);
pub const COLOR_MAGENTA:MESSAGEBOX_RESULT = MESSAGEBOX_RESULT(IDC_BLACK + 5);
pub const COLOR_YELLOW:MESSAGEBOX_RESULT = MESSAGEBOX_RESULT(IDC_BLACK + 6);
pub const COLOR_WHITE:MESSAGEBOX_RESULT = MESSAGEBOX_RESULT(IDC_WHITE);

pub const FIG_RECT:MESSAGEBOX_RESULT = MESSAGEBOX_RESULT(1008);
pub const FIG_ELLIPSE:MESSAGEBOX_RESULT = MESSAGEBOX_RESULT(1009);

pub const IDC_BLACK: i32 = 1000;
pub const IDC_WHITE: i32 = 1007;
pub const IDC_RECT: i32 = 1008;
pub const IDC_ELLIPSE: i32 = 1009;

pub const IDM_APP_ABOUT: i32 = 40001;